# Site settings
title: Lundberg Lab - Cell Profiling
email: emma.lundberg@scilifelab.se
pi: Emma Lundberg
description: > # this means to ignore newlines until "baseurl:"
  Spatial proteomics and cell biology
baseurl: "" # the subpath of your site, e.g. /blog/
#url: "http://cellprofiling.github.io/" # the base hostname & protocol for your site
url: "http://localhost:4000" # the base hostname & protocol for your site
twitter_username: CellProfiling
github_username:  CellProfiling

# Build settings
markdown: kramdown

# Collections
collections:
  people:
    output: true
  jobs:
    output: true
